steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cicd2:$SHORT_SHA', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cicd2:$SHORT_SHA']
 
# # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy','cicd2', '--region=asia-south1','--platform=managed', '--image=gcr.io/$PROJECT_ID/cicd2:$SHORT_SHA']

